[project]
name = "transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "assemblyai>=0.37.0",
    "fire>=0.7.0",
    "loguru>=0.7.3",
    "mcp>=1.6.0",
]
